name: CICD

on:
  push:
    branches: [cicd-docker-ec2]

jobs:
  build:
    steps:
      - name: checkout source
      - uses: action/checkout@v3
      - name: login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: docker build -t jvvenkateshdh/nodejs-demo-app .
      - name: publish image to docker hub
        run: docker push jvvenkateshdh/nodejs-demo-app:latest

deploy:
  needs: build
  runs-on: [aws-ec2]
  steps:
    - name: pull image from docker hub
      run: docker pull jvvenkateshdh/nodejs-demo-app:latest
    - name: delete old container
      run: docker rm -f nodejs-demo-app-container
    - name: Run docker container
      run: docker run -d -p 5000:5000 --name nodejs-demo-app-container jvvenkateshdh/nodejs-demo-app


  

